using System.Data.Common;
using System.Text;
using Dapper;

namespace HowlDev.IO.OOSql;

/// <summary>
/// Holds functions/parameters to get completed queries. 
/// </summary>
/// <typeparam name="T">ISqlTable</typeparam>
/// <typeparam name="D">Arbitrary DTO</typeparam>
public class CompleteQuery<T, D> where T : ISqlTable {
    private string sql;
    internal CompleteQuery() {
        StringBuilder builder = new();
        builder.Append("select");
        var baseTable = Activator.CreateInstance<T>().BaseDTO.GetProperties().Select(a => a.Name.ToLower());
        var obj = typeof(D).GetProperties().Select(a => a.Name.ToLower()).Where(a => baseTable.Contains(a));
        
        if (baseTable.Count() != obj.Count()) {
            throw new InvalidCastException("Not all properties on the provided class have an equivalent.");
        }

        foreach (string item in obj) {
            builder.Append($" {item} ");
        }

        builder.Append("from ");
        builder.Append(typeof(T).Name[..^5]);
        sql = builder.ToString();
    }

    /// <summary>
    /// Inspect the SQL generated by the query.
    /// </summary>
    public string Sql => sql;

    /// <summary>
    /// Get the result from a single-row query. 
    /// </summary>
    public async Task<D> QuerySingleAsync(DbConnection conn) {
        return await conn.QuerySingleAsync<D>(Sql);
    }
}
