using System.Data.Common;
using System.Reflection;
using System.Text;
using Dapper;

namespace HowlDev.IO.OOSql;

/// <summary>
/// Holds functions/parameters to get completed queries. 
/// </summary>
/// <typeparam name="T">ISqlTable</typeparam>
/// <typeparam name="D">Arbitrary DTO</typeparam>
public class CompleteQuery<T, D> where T : ISqlTable {
    private string sql;
    internal CompleteQuery() {
        StringBuilder builder = new();
        builder.Append("select");
        var obj = typeof(D).GetProperties();
        foreach (PropertyInfo item in obj) {
            builder.Append($" {item.Name} ");
        }

        builder.Append("from ");
        builder.Append(typeof(T).Name[..^5]);
        sql = builder.ToString();
    }

    /// <summary>
    /// Inspect the SQL generated by the query.
    /// </summary>
    public string Sql => sql;

    /// <summary>
    /// Get the result from a single-row query. 
    /// </summary>
    public async Task<D> QuerySingleAsync(DbConnection conn) {
        return await conn.QuerySingleAsync<D>(Sql);
    }
}
