// using System.Data;
// using System.Data.Common;

// // This file was generated by AI.

// /* 
// Usage: 

// var conn = new DbConnectionOverride { ConnectionString = "mock" };
// conn.Open();

// // ... execute Dapper commands ...

// // Check what was executed:
// foreach (var cmd in conn.ExecutionHistory) {
//     Console.WriteLine($"SQL: {cmd.CommandText}");
//     foreach (var param in cmd.Parameters) {
//         Console.WriteLine($"  {param.Name} = {param.Value}");
//     }
// }

// // Or just get the SQL queries
// var queries = conn.ExecutedQueries;

// // Clear history for next test
// conn.ClearHistory();
// */

// internal class DbConnectionOverride : DbConnection {
//     private string _connectionString = "";
//     private ConnectionState _state = ConnectionState.Closed;
//     private readonly List<ExecutedCommand> _executionHistory = new();

//     public override string ConnectionString {
//         get => _connectionString;
//         set => _connectionString = value;
//     }

//     public override string Database => "MockDatabase";
//     public override string DataSource => "MockDataSource";
//     public override string ServerVersion => "1.0";
    
//     public override ConnectionState State => _state;

//     /// <summary>
//     /// Gets all executed commands in order
//     /// </summary>
//     public IReadOnlyList<ExecutedCommand> ExecutionHistory => _executionHistory.AsReadOnly();

//     /// <summary>
//     /// Gets all SQL queries that have been executed
//     /// </summary>
//     public IEnumerable<string> ExecutedQueries => _executionHistory.Select(e => e.CommandText);

//     /// <summary>
//     /// Clears the execution history
//     /// </summary>
//     public void ClearHistory() => _executionHistory.Clear();

//     public override void ChangeDatabase(string databaseName) {
//         // Mock implementation - just accept it
//     }

//     public override void Close() {
//         _state = ConnectionState.Closed;
//     }

//     public override void Open() {
//         _state = ConnectionState.Open;
//     }

//     protected override DbTransaction BeginDbTransaction(IsolationLevel isolationLevel) {
//         return new MockDbTransaction(this, isolationLevel);
//     }

//     protected override DbCommand CreateDbCommand() {
//         return new MockDbCommand(this);
//     }

//     internal void LogExecutedCommand(string commandText, CommandType commandType, List<MockDbParameter> parameters) {
//         _executionHistory.Add(new ExecutedCommand {
//             CommandText = commandText,
//             CommandType = commandType,
//             Parameters = parameters.Select(p => new ParameterSnapshot {
//                 Name = p.ParameterName,
//                 Value = p.Value,
//                 DbType = p.DbType
//             }).ToList(),
//             ExecutedAt = DateTime.UtcNow
//         });
//     }
// }

// internal class ExecutedCommand {
//     public string CommandText { get; set; }
//     public CommandType CommandType { get; set; }
//     public List<ParameterSnapshot> Parameters { get; set; }
//     public DateTime ExecutedAt { get; set; }

//     public override string ToString() {
//         var paramStr = Parameters.Count > 0 ? $" [{string.Join(", ", Parameters.Select(p => $"{p.Name}={p.Value}"))}]" : "";
//         return $"{CommandText}{paramStr}";
//     }
// }

// internal class ParameterSnapshot {
//     public string Name { get; set; }
//     public object Value { get; set; }
//     public DbType DbType { get; set; }
// }

// internal class MockDbParameter : DbParameter {
//     private object _value;

//     public override DbType DbType { get; set; }
//     public override ParameterDirection Direction { get; set; }
//     public override bool IsNullable { get; set; }
//     public override string ParameterName { get; set; }
//     public override string SourceColumn { get; set; }
//     public override DataRowVersion SourceVersion { get; set; }
//     public override object Value {
//         get => _value;
//         set => _value = value;
//     }

//     public override int Size {
//         get {
//             throw new NotImplementedException();
//         }

//         set {
//             throw new NotImplementedException();
//         }
//     }

//     public override bool SourceColumnNullMapping {
//         get {
//             throw new NotImplementedException();
//         }

//         set {
//             throw new NotImplementedException();
//         }
//     }

//     public override void ResetDbType() {
//         DbType = DbType.String;
//     }
// }

// internal class MockDbCommand : DbCommand {
//     private readonly DbConnectionOverride _connection;
//     private string _commandText = "";
//     private CommandType _commandType = CommandType.Text;
//     private int _commandTimeout = 30;
//     private readonly List<MockDbParameter> _parameters = new();

//     public MockDbCommand(DbConnectionOverride connection) {
//         _connection = connection;
//     }

//     public override string CommandText {
//         get => _commandText;
//         set => _commandText = value;
//     }

//     public override int CommandTimeout {
//         get => _commandTimeout;
//         set => _commandTimeout = value;
//     }

//     public override CommandType CommandType {
//         get => _commandType;
//         set => _commandType = value;
//     }

//     public override UpdateRowSource UpdatedRowSource { get; set; }

//     protected override DbConnection DbConnection {
//         get => _connection;
//         set { }
//     }

//     protected override DbParameterCollection DbParameterCollection {
//         get => new MockDbParameterCollection(_parameters);
//     }

//     protected override DbTransaction DbTransaction { get; set; }

//     public override bool DesignTimeVisible {
//         get {
//             throw new NotImplementedException();
//         }

//         set {
//             throw new NotImplementedException();
//         }
//     }

//     public override void Cancel() {
//         // Mock implementation
//     }

//     public override int ExecuteNonQuery() {
//         _connection.LogExecutedCommand(_commandText, _commandType, _parameters);
//         return 0; // Mock: return 0 rows affected
//     }

//     public override object ExecuteScalar() {
//         _connection.LogExecutedCommand(_commandText, _commandType, _parameters);
//         return null; // Mock: return null
//     }

//     protected override DbDataReader ExecuteDbDataReader(CommandBehavior behavior) {
//         _connection.LogExecutedCommand(_commandText, _commandType, _parameters);
//         return new MockDbDataReader();
//     }

//     public override void Prepare() {
//         // Mock implementation
//     }

//     protected override DbParameter CreateDbParameter() {
//         return new MockDbParameter();
//     }
// }

// internal class MockDbParameterCollection : DbParameterCollection {
//     private readonly List<MockDbParameter> _parameters;

//     public MockDbParameterCollection(List<MockDbParameter> parameters) {
//         _parameters = parameters;
//     }

//     public override int Count => _parameters.Count;
//     public override object SyncRoot => _parameters;

//     public override int Add(object value) {
//         _parameters.Add((MockDbParameter)value);
//         return _parameters.Count - 1;
//     }

//     public override void AddRange(System.Array values) {
//         _parameters.AddRange(values.Cast<MockDbParameter>());
//     }

//     public override void Clear() {
//         _parameters.Clear();
//     }

//     public override bool Contains(object value) {
//         return _parameters.Contains((MockDbParameter)value);
//     }

//     public override bool Contains(string value) {
//         return _parameters.Any(p => p.ParameterName == value);
//     }

//     public override void CopyTo(System.Array array, int index) {
//         _parameters.CopyTo((MockDbParameter[])array, index);
//     }

//     public override System.Collections.IEnumerator GetEnumerator() {
//         return _parameters.GetEnumerator();
//     }

//     public override int IndexOf(object value) {
//         return _parameters.IndexOf((MockDbParameter)value);
//     }

//     public override int IndexOf(string parameterName) {
//         return _parameters.FindIndex(p => p.ParameterName == parameterName);
//     }

//     public override void Insert(int index, object value) {
//         _parameters.Insert(index, (MockDbParameter)value);
//     }

//     public override void Remove(object value) {
//         _parameters.Remove((MockDbParameter)value);
//     }

//     public override void RemoveAt(int index) {
//         _parameters.RemoveAt(index);
//     }

//     public override void RemoveAt(string parameterName) {
//         var index = IndexOf(parameterName);
//         if (index >= 0) RemoveAt(index);
//     }

//     protected override DbParameter GetParameter(int index) {
//         return _parameters[index];
//     }

//     protected override DbParameter GetParameter(string parameterName) {
//         return _parameters.FirstOrDefault(p => p.ParameterName == parameterName);
//     }

//     protected override void SetParameter(int index, DbParameter value) {
//         _parameters[index] = (MockDbParameter)value;
//     }

//     protected override void SetParameter(string parameterName, DbParameter value) {
//         var index = IndexOf(parameterName);
//         if (index >= 0) _parameters[index] = (MockDbParameter)value;
//     }
// }

// internal class MockDbTransaction : DbTransaction {
//     private readonly DbConnectionOverride _connection;

//     public MockDbTransaction(DbConnectionOverride connection, IsolationLevel isolationLevel) {
//         _connection = connection;
//         IsolationLevel = isolationLevel;
//     }

//     public override IsolationLevel IsolationLevel { get; }

//     protected override DbConnection DbConnection => _connection;

//     public override void Commit() {
//         // Mock implementation
//     }

//     public override void Rollback() {
//         // Mock implementation
//     }
// }

// internal class MockDbDataReader : DbDataReader {
//     public override int Depth => 0;
//     public override int FieldCount => 0;
//     public override bool HasRows => false;
//     public override bool IsClosed => false;
//     public override int RecordsAffected => 0;

//     public override object this[string name] => throw new NotImplementedException();

//     public override object this[int ordinal] => throw new NotImplementedException();

//     public override bool GetBoolean(int ordinal) => false;
//     public override byte GetByte(int ordinal) => 0;
//     public override long GetBytes(int ordinal, long dataOffset, byte[] buffer, int bufferOffset, int length) => 0;
//     public override char GetChar(int ordinal) => '\0';
//     public override long GetChars(int ordinal, long dataOffset, char[] buffer, int bufferOffset, int length) => 0;
//     public override string GetDataTypeName(int ordinal) => "string";
//     public override DateTime GetDateTime(int ordinal) => DateTime.MinValue;
//     public override decimal GetDecimal(int ordinal) => 0;
//     public override double GetDouble(int ordinal) => 0;
//     public override Type GetFieldType(int ordinal) => typeof(string);
//     public override float GetFloat(int ordinal) => 0;
//     public override Guid GetGuid(int ordinal) => Guid.Empty;
//     public override short GetInt16(int ordinal) => 0;
//     public override int GetInt32(int ordinal) => 0;
//     public override long GetInt64(int ordinal) => 0;
//     public override string GetName(int ordinal) => "";
//     public override int GetOrdinal(string name) => 0;
//     public override string GetString(int ordinal) => "";
//     public override object GetValue(int ordinal) => null;
//     public override int GetValues(object[] values) => 0;
//     public override bool IsDBNull(int ordinal) => true;
//     public override bool NextResult() => false;
//     public override bool Read() => false;
//     public override System.Collections.IEnumerator GetEnumerator() => Enumerable.Empty<object>().GetEnumerator();
// }
